### ISSUE TITLE
新規登録時、性別を未選択で登録を行うとUndefined index: genderとなる

### ISSUE THREAD

**Issue by Masashige-T** [Masashige-T/SOKUNE#16]
migration定義時にnullを承認していなかったことが問題かと思ったのですが一度nullabel()を付与しmigrationをし直しても同様のエラーが表示された

**Comment by ttrweb** [comment]
トラブル発生

**Comment by ttrweb** [comment]
@Masashige-T 
nullabel() やめて入力必須にしましょう
選択項目に未選択を追加したらいいんじゃないかな

**Comment by Masashige-T** [comment]
@ttrweb 
ありがとうございます
その方向で修正します。

**Comment by ttrweb** [comment]
![nichijou2](https://user-images.githubusercontent.com/57083948/98124549-b0af5200-1ef6-11eb-9e42-24d5c0975df7.gif)

**Comment by Masashige-T** [comment]
性別欄に未選択を追加し、未選択にデフォルトでチェックされるようにし、genderカラムに0が格納されることを確認しました
![スクリーンショット 2020-11-04 23 54 03](https://user-images.githubusercontent.com/60108574/98126576-17356f80-1ef9-11eb-8f67-2c1a717f44f5.png)

同時に生年月日を取得することをやめ、birthdayカラムを削除します

PRと同時にcloseします
