### ISSUE TITLE
商品データに付与するカテゴリーをテーブルとして用意する

### ISSUE THREAD

**Issue by Masashige-T** [Masashige-T/SOKUNE#4]
## 現在想定している商品テーブル

| Products   |
|----------  |
| id               |
|name          |
|category_id|
|price           |
|description|
|stock          |

このcategory_idのテーブルを作りたい

## テーブルを用意する理由

商品データが確定でなく、今後も商品の追加、カテゴリーの変更の可能性があるため

## 考えているスキーマ
```
Schema::create('categories', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('name');
});
```
カテゴリーに時刻等は必要なさそうなので標準で入るtimestampsは消しました

**Comment by ttrweb** [comment]
@Masashige-T 
【imo】
id:1, name:六角枕ってのがあって、後日枕はひらがな表記でcategoriesから抽出したいってなったら、idを新規で追加するのはややこしいので、各idにnameがいつ更新されたかの情報は残しても良いかと思いました
デフォルトだとTIMESTAMP カラムは NOT NULL なんで、抵抗なければとりあえずテーブルのカラムに追加はしてもいいんじゃないかな
https://dev.mysql.com/doc/refman/5.6/ja/timestamp-initialization.html

**Comment by Masashige-T** [comment]
@ttrweb 
確かに更新する可能性考えてませんでした
TIMESTAMPも入れましょう

**Comment by ttrweb** [comment]
変更に関するPRマージ後にclose
